//
//  ProductsPresenter.swift
//  ThreeBrothers
//
//  Created by Вячеслав Квашнин on 12.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol ProductsPresentationLogic {
    func presentSomething(response: Products.Something.Response)
}

class ProductsPresenter: ProductsPresentationLogic {
    
    weak var viewController: ProductsDisplayLogic?
    
    func presentSomething(response: Products.Something.Response) {
        let viewModel = Products.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
