//
//  ProductsInteractor.swift
//  ThreeBrothers
//
//  Created by Вячеслав Квашнин on 12.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol ProductsBusinessLogic {
    func doSomething(request: Products.Something.Request)
}

protocol ProductsDataStore {
    
}

class ProductsInteractor: ProductsBusinessLogic, ProductsDataStore {
    
    var presenter: ProductsPresentationLogic?
    var worker: ProductsWorker?
    
    func doSomething(request: Products.Something.Request) {
        worker = ProductsWorker()
        worker?.doSomeWork()
        
        let response = Products.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
